[package]
name = "netidx-excel"
version = "0.1.0"
edition = "2021"

[dependencies]
com = { version = "0.6", features = ["production"] }
winapi = { version = "0.3", features = ["oaidl", "winuser", "winnt"]}
oaidl = "0.2"
log = "0.4"
simplelog = "0.11"
once_cell = "1"

[lib]
crate-type = ["rlib", "cdylib"]
